server:
  port: 8080
  shutdown: graceful
  servlet:
    encoding:
      force: true
  compression:
    enabled: true
    min-response-size: 1024
  undertow:
    threads:
      io: 8
      worker: 128
    buffer-size: 1024
    direct-buffers: true
    accesslog:
      enabled: true
      dir: logs
      pattern: combined
      prefix: pub-reader_access.

spring:
  config:
    activate:
      on-profile: dev
  jackson:
    default-property-inclusion: non_null
    generator:
      write-bigdecimal-as-plain: true
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:config/sharding-dev.yml

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: cn.scifi.pubreader.infrastructure.common.serialize.CodedEnumTypeHandler

app:
  api-prefix: /api
  rsa:
    expires-in: 7200
    private-key: classpath:certs/private-key.pem
    public-key: classpath:certs/public-key.pem
  allow-origins:
    - http://localhost:3000
    - http://127.0.0.1:3000
  allowlist:
    - /**
    - /api/v3/api-docs/**
    - /swagger-ui/**
    - /api/v1/auth/**

logging:
  config: classpath:logback-spring.xml


