dataSources:
  ds_shared:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:33306/novels?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&rewriteBatchedStatements=true&useAffectedRows=true&useSSL=false&requireSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:33306/novels_0?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&rewriteBatchedStatements=true&useAffectedRows=true&useSSL=false&requireSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
  ds_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:33306/novels_1?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&rewriteBatchedStatements=true&useAffectedRows=true&useSSL=false&requireSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 12345678

rules:
- !SHARDING
  tables:
    novel_chapter:
      actualDataNodes: ds_$->{0..1}.novel_chapter_$->{0..5}
      databaseStrategy:
        standard:
          shardingColumn: book_id
          shardingAlgorithmName: database_inline
      tableStrategy:
        standard:
          shardingColumn: id
          shardingAlgorithmName: chapter_table_inline
      keyGenerateStrategy:
        column: id
        keyGeneratorName: snowflake
    novel_chapter_content:
      actualDataNodes: ds_$->{0..1}.novel_chapter_content_$->{0..5}
      databaseStrategy:
        standard:
          shardingColumn: book_id
          shardingAlgorithmName: database_inline
      tableStrategy:
        standard:
          shardingColumn: chapter_id
          shardingAlgorithmName: content_table_inline
  bindingTables:
    - novel_chapter,novel_chapter_content
  shardingAlgorithms:
    database_inline:
      type: INLINE
      props:
        algorithm-expression: ds_${book_id % 2}
    chapter_table_inline:
      type: INLINE
      props:
        algorithm-expression: novel_chapter_${id % 6}
    content_table_inline:
      type: INLINE
      props:
        algorithm-expression: novel_chapter_content_${chapter_id % 6}
  keyGenerators:
    snowflake:
      type: SNOWFLAKE
- !SINGLE
  tables:
    - ds_shared.*
  defaultDataSource: ds_shared

props:
  sql-show: true
  max-connections-size-per-query: 5
