// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"pub-reader/internal"
)

// Injectors from wire.go:

// nolint:all
func BuildContainer() (*internal.Container, error) {
	container := &internal.Container{}
	return container, nil
}
